import Footer from "./componentes/footer/page";
import Header from "./componentes/header/header";



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
       <Header/>
        <main>{children}</main>
        <Footer/>
        </body>
    </html>
  )
}
